version: 1.0-beta

config:
  expose: 3000
  url: https://webhook.melcher.io

health_check:
  period: "0 5 * * * * *"

  steps:
    - uses: docker/ping

route:
  path: /github

  pipeline:
    - uses: http_validator_wasm
      name: Validate if the event comes from GitHun
      with:
        wasm: ./target/wasm32-wasi/release/github_accept_webhook.wasm
      arguments:
        secret: ${{ env.GITHUB_TOKEN }}

  steps:
    - uses: docker/stop_container
      name: Stop the container
      with:
        container_name: my_website

    - uses: docker/build_image
      name: Build the new image
      with:
        image_name: my_website_image
        dockerfile: ./Dockerfile.auto

    - uses: docker/start_image
      name: Start new image as container
      with:
        container_name: my_website
        image_name: my_website_image
        networks: personal_website_internal_network
        ports: 8080:80
        auto_remove: true
