[package]
name = "wasm_shared"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
anyhow = { workspace = true }
tracing-subscriber = { workspace = true }
scopeguard.workspace = true
