name: CI

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "**.rs"
      - "**Cargo.**"
      - ".github/workflows/ci.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  build_wasm:
    strategy:
      matrix:
        wasm_modules: [github_accept_webhook]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: wasm32-wasi

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: wasm-${{ matrix.wasm_modules }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build wasm
        run: cargo build --package ${{ matrix.wasm_modules }} --target wasm32-wasi

      - name: Test
        run: cargo test --package ${{ matrix.wasm_modules }}
